-- DROP DATABASE Project;
CREATE DATABASE IF NOT EXISTS Project;
use Project; 

#USE bookstore;

CREATE TABLE IF NOT EXISTS `city`(
`CITY_ID` INTEGER NOT NULL DEFAULT 0,
`COUNTRY_ID` INTEGER NOT NULL DEFAULT 0,
`CITY_NAME` varchar(20) NOT NULL,
PRIMARY KEY (`CITY_ID`)
);

CREATE TABLE IF NOT EXISTS `customer`(
  `CUSTOMER_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(40) NOT NULL,
  `LAST_NAME` varchar(40) NOT NULL, 
  `EMAIL` varchar(40) NOT NULL,
  `ORDER_ID` INTEGER DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
);

CREATE TABLE IF NOT EXISTS `employee`(
`EMPLOYEE_ID` INTEGER NOT NULL DEFAULT 0,
`EMPLOYEE_FIRST_NAME` varchar(20) NOT NULL,
`EMPLOYEE_LAST_NAME` varchar(20) NOT NULL,
`ADDRESS_ID` INTEGER NOT NULL,
`EMAIL` varchar(20) DEFAULT NULL,
PRIMARY KEY(`EMPLOYEE_ID`)
); 

CREATE TABLE IF NOT EXISTS `book`(
# VER ETSA MERDA DEFAULT
`ISBN` varchar(17) NOT NULL, 
`TITLE` varchar(40) NOT NULL,
`PUBLISHER_ID` INTEGER NOT NULL DEFAULT 0,
`RATING` INTEGER DEFAULT NULL,
 PRIMARY KEY (`ISBN`)
);

CREATE TABLE IF NOT EXISTS `author` (
`AUTHOR_ID` INTEGER NOT NULL DEFAULT 0,
`AUTHOR_FIRST_NAME` varchar(40) NOT NULL,
`AUTHOR_LAST_NAME` varchar(40) NOT NULL,
 PRIMARY KEY (`AUTHOR_ID`)
);

CREATE TABLE IF NOT EXISTS `publisher`(
`PUBLISHER_ID` INTEGER NOT NULL DEFAULT 0,
`PUBLISHER_NAME` varchar(40) NOT NULL,
PRIMARY KEY (`PUBLISHER_ID`)
);

CREATE TABLE IF NOT EXISTS `author_book`(
`ISBN` varchar(17) NOT NULL, 
`AUTHOR_ID` INTEGER NOT NULL,
FOREIGN KEY (`ISBN`) references book(`ISBN`),
FOREIGN KEY (`AUTHOR_ID`) references author(`AUTHOR_ID`),
PRIMARY KEY (`ISBN`, `AUTHOR_ID`)
);


CREATE TABLE IF NOT EXISTS `rating`(
`ISBN` varchar(17) NOT NULL, 
`CUSTOMER_ID` INTEGER NOT NULL,
`RATING` ENUM('1','2','3','4','5') NOT NULL,
FOREIGN KEY (`ISBN`) references book(`ISBN`),
FOREIGN KEY (`CUSTOMER_ID`) references customer(`CUSTOMER_ID`),
PRIMARY KEY (`ISBN`, `CUSTOMER_ID`)
); 

CREATE TABLE IF NOT EXISTS `address`(
`ADDRESS_ID` INTEGER NOT NULL DEFAULT 0,
`ADDRESS` varchar(50) NOT NULL,
`POSTAL_CODE` varchar(50) NOT NULL,
`CITY_ID` INTEGER NOT NULL,
FOREIGN KEY (`CITY_ID`) references city(`CITY_ID`),
PRIMARY KEY (`ADDRESS_ID`)
); 


CREATE TABLE IF NOT EXISTS `purchase`(
`PURCHASE_ID` INTEGER NOT NULL AUTO_INCREMENT,
`ADDRESS_ID` INTEGER NOT NULL,
`CUSTOMER_ID` INTEGER NOT NULL,
`ORDER_DATE` date NOT NULL,
`EMPLOYEE_ID` INTEGER NOT NULL,
`AMOUNT` decimal NOT NULL,
FOREIGN KEY (`CUSTOMER_ID`) references customer(`CUSTOMER_ID`),
FOREIGN KEY (`ADDRESS_ID`) references address(`ADDRESS_ID`),
FOREIGN KEY (`EMPLOYEE_ID`) references employee(`EMPLOYEE_ID`),
PRIMARY KEY (`PURCHASE_ID`)
);

CREATE TABLE IF NOT EXISTS `book_purchase`(
`BOOK_PURCHASE_ID` INTEGER NOT NULL AUTO_INCREMENT, 
`PURCHASE_ID` INTEGER NOT NULL,
`ISBN` varchar(17) NOT NULL, 
`QUANTITY` INTEGER NOT NULL,
FOREIGN KEY (`PURCHASE_ID`) REFERENCES purchase(`PURCHASE_ID`),
FOREIGN KEY (`ISBN`) REFERENCES book(`ISBN`),
PRIMARY KEY (`BOOK_PURCHASE_ID`)
); 

CREATE TABLE IF NOT EXISTS `publisher_book`(
`PUBLISHER_ID` INTEGER NOT NULL,
`ISBN` varchar(17) NOT NULL,
FOREIGN KEY (`PUBLISHER_ID`) references publisher(`PUBLISHER_ID`),
FOREIGN KEY (`ISBN`) references book(`ISBN`),
PRIMARY KEY (`PUBLISHER_ID` , `ISBN`)
);

